---
applications:
  - name: ccte-api
    routes:
      - route: ccte-api-p.app.cloud.gov
      - route: ccte-api-p.apps.internal
    memory: 2G
    instances: 1
    random-route: false
    path: target/chemical.jar
    buildpacks:
    - https://github.com/cloudfoundry/java-buildpack
    env:
      SPRING_PROFILES_ACTIVE: cloud,apikey
      JBP_CONFIG_SPRING_AUTO_RECONFIGURATION: '{ enabled: false }'
      JBP_CONFIG_OPEN_JDK_JRE: '{ jre: { version: 11.+ }, memory_calculator: { stack_threads: 25 } }'