
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  application:
    name: hazard
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  task:
    execution:
      thread-name-prefix: chemical-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: hazard-scheduling-
      pool:
        size: 2
  output:
    ansi:
      enabled: always

springdoc:
  show-actuator: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  servlet:
    session:
      cookie:
        http-only: true
  port: 9300
  shutdown: graceful # this will allow to finish currently processing requrst before shutdown. THis is very important for cloud/Kube environment

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration
#
# ===================================================================

application:
  api-key-name: "x-api-key"
  api-env: "Production Environment"
  api-url: "https://api-ccte.epa.gov"
  batch-size: 200
# CORS is disabled by default on microservices, as you should access them through a gateway.
# If you want to enable it, please uncomment the configuration below.
# cors:
#   allowed-origins: "http://localhost:9000,https://localhost:9000"
#   allowed-methods: "*"
#   allowed-headers: "*"
#   exposed-headers: "Authorization,Link,X-Total-Count"
#   allow-credentials: true
#   max-age: 1800