package gov.epa.ccte.api.hazard.springdocexamples.hazard;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import gov.epa.ccte.api.hazard.dto.HazardDto;
public class HazardDtoExample extends HazardDto {
    @JsonCreator // Jackson will use this constructor during deserialization
    public HazardDtoExample(@JsonProperty("id") Integer id, @JsonProperty("dtxsid") String dtxsid, @JsonProperty("priorityId") Integer priorityId, @JsonProperty("source") String source, @JsonProperty("subsource") String subsource,  @JsonProperty("sourceUrl") String sourceUrl, @JsonProperty("subsourceUrl") String subsourceUrl, @JsonProperty("riskAssessmentClass") String riskAssessmentClass, @JsonProperty("toxvalType") String toxvalType, @JsonProperty("toxvalSubtype") String toxvalSubtype, @JsonProperty("toxvalNumeric") Double toxvalNumeric, @JsonProperty("toxvalNumericQualifier") String toxvalNumericQualifier, @JsonProperty("toxvalUnits") String toxvalUnits, @JsonProperty("studyType") String studyType, @JsonProperty("studyDurationClass") String studyDurationClass, @JsonProperty("studyDurationValue") Double studyDurationValue, @JsonProperty("studyDurationUnits") String studyDurationUnits, @JsonProperty("strain") String strain, @JsonProperty("sex") String sex, @JsonProperty("population") String population, @JsonProperty("exposureRoute") String exposureRoute, @JsonProperty("exposureMethod") String exposureMethod, @JsonProperty("exposureForm") String exposureForm, @JsonProperty("media") String media, @JsonProperty("lifestage") String lifestage, @JsonProperty("generation") String generation, @JsonProperty("year") String year, @JsonProperty("criticalEffect") String criticalEffect, @JsonProperty("detailText") String detailText, @JsonProperty("supercategory") String supercategory, @JsonProperty("speciesCommon") String speciesCommon, @JsonProperty("humanEcoNt") String humanEcoNt) {
        super(id, dtxsid, priorityId, source, subsource, sourceUrl, subsourceUrl, riskAssessmentClass, toxvalType, toxvalSubtype, toxvalNumeric, toxvalNumericQualifier, toxvalUnits, studyType, studyDurationClass, studyDurationValue, studyDurationUnits, strain, sex, population, exposureRoute, exposureMethod, exposureForm, media, lifestage, generation, year, criticalEffect, detailText, supercategory, speciesCommon, humanEcoNt);
    }
}
