-- ********************************************************************************************
-- cancer_summary data
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020076', 'CalEPA', '-', 'Known human carcinogen', 'https://oehha.ca.gov/proposition-65/proposition-65-list', 1, 5);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020076', 'EPA OPP', '-', 'Group B2 Probable Human Carcinogen ', 'http://www.epa.gov/pesticides/carlist/', 1, 6);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020076', 'IARC', '-', 'Group 3 - Not classifiable as to its carcinogenicity to humans', 'https://monographs.iarc.who.int/list-of-classifications/', 1, 7);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020076', 'NIOSH', 'inhalation', 'potential occupational carcinogen', 'https://www.cdc.gov/niosh/topics/cancer/npotocca.html', 1, 8);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020076', 'NTP RoC', '-', 'Reasonably Anticipated to be a Human Carcinogen', 'https://ntp.niehs.nih.gov/whatwestudy/assessments/cancer/roc/index.html#toc1', 1, 9);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020153', 'CalEPA', '-', 'Known human carcinogen', 'https://oehha.ca.gov/proposition-65/proposition-65-list', 1, 12);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020153', 'IARC', '-', 'Group 2A - Probably carcinogenic to humans', 'https://monographs.iarc.who.int/list-of-classifications/', 1, 13);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020153', 'IRIS', '-', 'B2 (Probable human carcinogen - based on sufficient evidence of carcinogenicity in animals)', 'https://cfpub.epa.gov/ncea/iris/search/index.cfm', 1, 14);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020319', 'CalEPA', '-', 'Known human carcinogen', 'https://oehha.ca.gov/proposition-65/proposition-65-list', 1, 23);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020319', 'EPA OPP', '-', 'Group B2 Probable Human Carcinogen ', 'http://www.epa.gov/pesticides/carlist/', 1, 24);
INSERT INTO ms.cancer_summary (dtxsid, source, exposure_route, cancer_call, url, rn, id) VALUES ('DTXSID0020319', 'IARC', '-', 'Group 2B - Possibly carcinogenic to humans', 'https://monographs.iarc.who.int/list-of-classifications/', 1, 25);
-- ********************************************************************************************
-- genetox_details data
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221979, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'E. coli WP2 uvr A', null, 'negative', 2001, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221966, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1535, TA 1537, TA 98 and TA', null, 'negative', 1982, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221967, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1535, TA 1537, TA 98 and TA', null, 'negative', 1997, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221968, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1535, TA 1537, TA 98 and TA', null, 'negative', 2001, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221974, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1538', null, 'negative', 1982, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221976, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1538', null, 'negative', 1997, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221969, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'in vitro mammalian chromosome aberration test', 'with and without', 'Chinese hamster Ovary (CHO)', null, 'negative', 2001, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221971, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'in vitro mammalian chromosome aberration test', 'with and without', 'lymphocytes:', null, 'negative', 2011, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221970, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'mammalian cell gene mutation assay', 'with and without', 'mouse lymphoma L5178Y cells', null, 'negative', 2009, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1221972, 'DTXSID00100670', 'eChemPortal', 'in vitro', 'mammalian cell gene mutation assay', 'with and without', 'mouse lymphoma L5178Y cells', null, 'negative', 2010, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1194574, 'DTXSID00109022', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1535, TA 1537, TA 98 and TA', null, 'negative', 1990, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1194575, 'DTXSID00109022', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1538', null, 'negative', 1990, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1194577, 'DTXSID00109022', 'eChemPortal', 'in vivo', 'micronucleus assay', null, 'mouse', 'CD-1', 'negative', 1991, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1200944, 'DTXSID00178076', 'eChemPortal', 'in vitro', 'bacterial reverse mutation assay', 'with and without', 'S. typhimurium TA 1535, TA 1537, TA 98 and TA', null, 'negative', 2009, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1200946, 'DTXSID00178076', 'eChemPortal', 'in vitro', 'in vitro mammalian cell gene mutation test using the Hprt and xprt genes', 'with and without', 'Chinese hamster lung fibroblasts (V79)', null, 'negative', 2017, 1);
INSERT INTO ms.genetox_details (id, dtxsid, source, assay_category, assay_type, metabolic_activation, species, strain, assay_result, year, rn) VALUES (1200945, 'DTXSID00178076', 'eChemPortal', 'in vitro', 'in vitro mammalian chromosome aberration test', 'with and without', 'lymphocytes: cultured peripheral human lympho', null, 'negative', 2012, 1);
-- ********************************************************************************************
-- genetox_summary data
INSERT INTO ms.genetox_summary (id, dtxsid, reports_pos, reports_neg, reports_other, ames, micronucleus, rn) VALUES (525278, 'DTXSID00101041', 2, 0, 0, null, null, 1);
INSERT INTO ms.genetox_summary (id, dtxsid, reports_pos, reports_neg, reports_other, ames, micronucleus, rn) VALUES (518798, 'DTXSID00108550', 0, 6, 0, null, 'negative', 1);
INSERT INTO ms.genetox_summary (id, dtxsid, reports_pos, reports_neg, reports_other, ames, micronucleus, rn) VALUES (526632, 'DTXSID00109168', 1, 8, 0, null, 'negative', 1);
INSERT INTO ms.genetox_summary (id, dtxsid, reports_pos, reports_neg, reports_other, ames, micronucleus, rn) VALUES (519415, 'DTXSID0025737', 5, 11, 0, null, 'negative', 1);
INSERT INTO ms.genetox_summary (id, dtxsid, reports_pos, reports_neg, reports_other, ames, micronucleus, rn) VALUES (520528, 'DTXSID0027775', 3, 7, 0, null, null, 1);
-- ********************************************************************************************
-- hazard data
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (9, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Developmental Toxicity Teratogenicity', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'developmental', 'NOEL', '-', 160, '=', 'mg/kg-day', 'developmental', '-', -999, '-', 'Sprague-Dawley', 'M/F', '-', '-', 'gavage', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Point of Departure', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:16.331957');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (26424, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'NOEC', '-', 10, '=', 'mg/L', 'acute', '-', 48, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Point of Departure', 'Water Flea', 'eco', 'app_pentaho', '2024-04-30 17:31:17.181247');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (26382, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'NOEC', '-', 1.8, '=', 'mg/L', 'acute', '-', 96, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Point of Departure', 'Rainbow Trout', 'eco', 'app_pentaho', '2024-04-30 17:31:17.181247');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (26393, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Repeated Dose Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'short-term', 'NOEL', '-', 40, '=', 'mg/kg-day', 'short-term', '-', 28, 'days', 'Sprague-Dawley', 'M/F', '-', 'oral', 'gavage', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Point of Departure', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:17.181247');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (26397, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'NOEC', '-', 10, '=', 'mg/L', 'acute', '-', 72, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Point of Departure', 'Dragonfly Family', 'eco', 'app_pentaho', '2024-04-30 17:31:17.181247');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (26400, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Developmental Toxicity Teratogenicity', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'developmental', 'NOEL', '-', 40, '=', 'mg/kg-day', 'developmental', '-', -999, '-', 'Sprague-Dawley', 'F', '-', '-', 'gavage', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Point of Departure', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:17.181247');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (26415, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Repeated Dose Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'short-term', 'NOAEL', '-', 160, '=', 'mg/kg-day', 'short-term', '-', 28, 'days', 'Sprague-Dawley', 'M/F', '-', 'oral', 'gavage', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Point of Departure', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:17.181247');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (26421, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'NOEC', '-', 1.8, '=', 'mg/L', 'acute', '-', 96, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Point of Departure', 'Rainbow Trout', 'eco', 'app_pentaho', '2024-04-30 17:31:17.181247');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649196, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 3200, '=', 'g/kg', 'acute', '-', 1, 'days', 'Sprague-Dawley', 'M', '-', 'oral', 'gavage', '-', '-', '-', '-', '1986', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649197, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Inhalation', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LC50', '-', 2300, '>', 'mg/L', 'acute', '-', 4, 'hours', 'Sprague-Dawley', 'M/F', '-', 'inhalation', 'vapor', '-', '-', '-', '-', '1986', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649198, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'LL50', '-', 10, '~', 'mg/L', 'acute', '-', 96, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Lethality Effect Level', 'Rainbow Trout', 'eco', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649199, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'LD50', '-', 2000, '>', 'mg/kg', 'acute', '-', -999, '-', 'New Zealand', '-', '-', 'dermal', '-', '-', '-', '-', '-', '1980', '-', 'HPVIS Details', 'Lethality Effect Level', 'Rabbit', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649200, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Dermal', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 2002, '>', 'mg/kg', 'acute', '-', 25, 'hours', 'Sprague-Dawley', 'M/F', '-', 'dermal', '-', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649201, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 4468, '=', 'mg/kg', 'acute', '-', 1, 'days', 'Sprague-Dawley', 'M/F', '-', 'oral', 'gavage', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649202, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Inhalation', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LC50', '-', 2300, '>', 'mg/L', 'acute', '-', 4, 'hours', 'Sprague-Dawley', 'M/F', '-', 'inhalation', 'vapor', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649203, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Dermal', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 2000, '>', 'mg/kg', 'acute', '-', -999, '-', 'New Zealand', 'M/F', '-', 'dermal', '-', '-', '-', '-', '-', '1986', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rabbit', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649204, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Dermal', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 2002, '>', 'mg/kg', 'acute', '-', -999, '-', 'Sprague-Dawley', 'M/F', '-', 'dermal', '-', '-', '-', '-', '-', '1986', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649205, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'LD50', '-', 3100, '=', 'mg/kg', 'acute', '-', -999, '-', 'Sprague-Dawley', '-', '-', 'oral', 'gavage', '-', '-', '-', '-', '1980', '-', 'HPVIS Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649206, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'LL50', '-', 4.5, '=', 'mg/L', 'acute', '-', 96, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Lethality Effect Level', 'Rainbow Trout', 'eco', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649207, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Dermal', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 2000, '>', 'mg/kg', 'acute', '-', 24, 'hours', 'New Zealand', 'M/F', '-', 'dermal', '-', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rabbit', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649208, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'LL50', '-', 4.5, '=', 'mg/L', 'acute', '-', 96, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Lethality Effect Level', 'Rainbow Trout', 'eco', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649209, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 3100, '=', 'g/kg', 'acute', '-', 1, 'days', 'Sprague-Dawley', 'F', '-', 'oral', 'gavage', '-', '-', '-', '-', '1986', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649210, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 3.2, '=', '-', 'acute', '-', 1, 'days', 'Sprague-Dawley', 'M', '-', 'oral', 'gavage', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649211, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'LL50', '-', 10, '>', 'mg/L', 'acute', '-', 96, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Lethality Effect Level', 'Rainbow Trout', 'eco', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649212, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 3.1, '=', '-', 'acute', '-', 1, 'days', 'Sprague-Dawley', 'F', '-', 'oral', 'gavage', '-', '-', '-', '-', '-', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (649213, 'DTXSID0029054', 5, 'ECHA IUCLID', 'Acute Toxicity Oral', 'https://echa.europa.eu/information-on-chemicals/registered-substances', '-', 'acute', 'LD50', '-', 4468, '=', 'mg/kg', 'acute', '-', 1, 'days', 'Sprague-Dawley', 'M/F', '-', 'oral', 'gavage', '-', '-', '-', '-', '1986', '-', 'ECHA IUCLID Details', 'Lethality Effect Level', 'Rat', 'human health', 'app_pentaho', '2024-04-30 17:31:37.512077');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (759896, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'EL50', '-', 23, '=', 'mg/L', 'acute', '-', 48, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Effect Level', 'Water Flea', 'eco', 'app_pentaho', '2024-04-30 17:31:41.028362');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (759888, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'EL50', '-', 24, '=', 'mg/L', 'acute', '-', 72, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Effect Level', 'Dragonfly Family', 'eco', 'app_pentaho', '2024-04-30 17:31:41.028362');
INSERT INTO ms.hazard (id, dtxsid, priority_id, source, subsource, source_url, subsource_url, risk_assessment_class, toxval_type, toxval_subtype, toxval_numeric, toxval_numeric_qualifier, toxval_units, study_type, study_duration_class, study_duration_value, study_duration_units, strain, sex, population, exposure_route, exposure_method, exposure_form, media, lifestage, generation, study_year, critical_effect, detail_text, supercategory, species_common, human_eco_nt, created_by, created_at) VALUES (759905, 'DTXSID0029054', 5, 'HPVIS', '-', 'https://chemview.epa.gov/chemview/', '-', 'acute', 'EL50', '-', 21, '=', 'mg/L', 'acute', '-', 72, 'hours', '-', '-', '-', '-', '-', '-', '-', '-', '-', '2004', '-', 'HPVIS Details', 'Effect Level', 'Dragonfly Family', 'eco', 'app_pentaho', '2024-04-30 17:31:41.028362');
-- ********************************************************************************************
-- skin-eye data
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2220667, 'DTXSID00100498', 'ECHA eChemPortal', 'Eye irritation', 'rabbit', 'New Zealand White', '2 (reliable with restrictions)', 'eye irritation: in vivo', ' OECD Guideline 405 (Acute Eye Irritation / Corrosion) according to', 'other: not classified Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1997, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2220666, 'DTXSID00100498', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Hartley', '2 (reliable with restrictions)', 'skin sensitisation: in vivo (non-LLNA)', ' according to OECD Guideline 406 (Skin Sensitisation)', 'sensitising Migrated information', 'High Frequency of Sensitization', 'H', 1993, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2220665, 'DTXSID00100498', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Hartley', '2 (reliable with restrictions)', 'skin sensitisation: in vivo (non-LLNA)', ' according to OECD Guideline 406 (Skin Sensitisation)', 'sensitising Migrated information', 'High Frequency of Sensitization', 'H', 1994, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2220664, 'DTXSID00100498', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Hartley', '2 (reliable with restrictions)', 'skin sensitisation: in vivo (non-LLNA)', ' according to OECD Guideline 406 (Skin Sensitisation)', 'sensitising Migrated information', 'High Frequency of Sensitization', 'H', 1995, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229768, 'DTXSID00100670', 'ECHA eChemPortal', 'Eye irritation', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'eye irritation: in vivo', ' OECD Guideline 405 (Acute Eye Irritation / Corrosion) according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1986, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229769, 'DTXSID00100670', 'ECHA eChemPortal', 'Eye irritation', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'eye irritation: in vivo', ' OECD Guideline 405 (Acute Eye Irritation / Corrosion) equivalent or similar to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1982, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229752, 'DTXSID00100670', 'ECHA eChemPortal', 'Eye irritation', 'rabbit', 'New Zealand White', '2 (reliable with restrictions)', 'eye irritation: in vivo', ' other guideline: Federal Hazardous Substances Act (FHSA) regulations; test for eye irritants equivalent or similar to', 'other: Slightly irritating Criteria used for interpretation of results: OECD GHS', 'Moderate or Mild Irritation', 'M', 1977, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229753, 'DTXSID00100670', 'ECHA eChemPortal', 'Eye irritation', 'rabbit', 'New Zealand White', '2 (reliable with restrictions)', 'eye irritation: in vivo', ' other guideline: Federal Hazardous Substances Act (FHSA) regulations; test for eye irritants equivalent or similar to', 'other: Slightly irritating Criteria used for interpretation of results: OECD GHS', 'Moderate or Mild Irritation', 'M', 1978, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229758, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1985, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229764, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1986, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229759, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1989, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229762, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1990, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229756, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1995, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229754, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) equivalent or similar to', 'other: Category 2 (irritant) based on GHS criteria', 'Severe Irritation', 'H', 1986, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229755, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) equivalent or similar to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1990, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229757, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) equivalent or similar to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1998, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229763, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '1 (reliable without restriction)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) The test was performed in two parts using two groups of 3 rabbits, with results for each part reported separately. according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1986, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229767, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin irritation / corrosion', 'rabbit', 'New Zealand White', '2 (reliable with restrictions)', 'skin irritation: in vivo', ' OECD Guideline 404 (Acute Dermal Irritation / Corrosion) according to', 'other: Not irritating Criteria used for interpretation of results: OECD GHS', 'Studies Indicate No Significant Irritation', 'L', 1989, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229774, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Dunkin-Hartley', '1 (reliable without restriction)', 'skin sensitisation: in vivo (non-LLNA)', ' according to OECD Guideline 406 (Skin Sensitisation)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 1990, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229770, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Dunkin-Hartley', '1 (reliable without restriction)', 'skin sensitisation: in vivo (non-LLNA)', ' according to OECD Guideline 406 (Skin Sensitisation)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 1992, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229773, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Dunkin-Hartley', '1 (reliable without restriction)', 'skin sensitisation: in vivo (non-LLNA)', ' according to OECD Guideline 406 (Skin Sensitisation) according to EU Method B.6 (Skin Sensitisation)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 1997, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229778, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Dunkin-Hartley', '1 (reliable without restriction)', 'skin sensitisation: in vivo (non-LLNA)', ' equivalent or similar to OECD Guideline 406 (Skin Sensitisation)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 1993, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229750, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Dunkin-Hartley', '2 (reliable with restrictions)', 'skin sensitisation: in vivo (non-LLNA)', ' according to OECD Guideline 406 (Skin Sensitisation)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 1986, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229779, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Hartley', '1 (reliable without restriction)', 'skin sensitisation: in vivo (non-LLNA)', ' equivalent or similar to OECD Guideline 406 (Skin Sensitisation)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 1993, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229771, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'guinea pig', 'Hartley', '1 (reliable without restriction)', 'skin sensitisation: in vivo (non-LLNA)', ' equivalent or similar to OECD Guideline 406 (Skin Sensitisation)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 1997, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2229777, 'DTXSID00100670', 'ECHA eChemPortal', 'Skin sensitisation', 'mouse', 'CBA', '1 (reliable without restriction)', 'skin sensitisation: in vivo (LLNA)', ' according to OECD Guideline 429 (Skin Sensitisation: Local Lymph Node Assay)', 'other: Not sensitising', 'Not likely to be sensitizing', 'L', 2002, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2234164, 'DTXSID001018307', 'ECHA eChemPortal', 'Eye irritation', 'rabbit', 'Himalayan', '1 (reliable without restriction)', 'eye irritation: in vivo', ' OECD Guideline 405 (Acute Eye Irritation / Corrosion) 2002-04-24 according to', 'not irritating Migrated informationCriteria used for interpretation of results: EU', 'Studies Indicate No Significant Irritation', 'L', 2012, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2234166, 'DTXSID001018307', 'ECHA eChemPortal', 'Skin sensitisation', 'mouse', 'NMRI', '1 (reliable without restriction)', 'skin sensitisation: in vivo (LLNA)', ' according to OECD Guideline 429 (Skin Sensitisation: Local Lymph Node Assay) 2010-07-22', 'not sensitising Migrated informationCriteria used for interpretation of results: EU', 'Not likely to be sensitizing', 'L', 2012, 1);
INSERT INTO ms.skin_eye (id, dtxsid, source, study_type, species, strain, reliability, endpoint, guideline, result_text, classification, score, year, rn) VALUES (2234168, 'DTXSID001018307', 'ECHA eChemPortal', 'Skin sensitisation', 'mouse', 'NMRI', '1 (reliable without restriction)', 'skin sensitisation: in vivo (LLNA)', ' according to OECD Guideline 429 (Skin Sensitisation: Local Lymph Node Assay) 2010-07-22', 'other: GHS criteria not met', 'Not likely to be sensitizing', 'L', 2012, 1);
