-- create schema
create schema toxval;

-- create tables

CREATE TABLE toxval.mv_cancer_summary (
	id int4 NOT NULL,
	export_date date NULL,
	data_version varchar(50) DEFAULT 'v9_4'::character varying NULL,
	dtxsid varchar(255) NULL,
	source varchar(255) NULL,
	exposure_route varchar(255) NULL,
	cancer_call varchar(255) NULL,
	url varchar(255) NULL,
	CONSTRAINT mv_cancer_summary_pkey1 PRIMARY KEY (id)
);

CREATE TABLE toxval.mv_genetox_details (
	id int4 NOT NULL,
	export_date date NULL,
	data_version varchar(50) DEFAULT 'v9_4'::character varying NULL,
	aggregate_study_type varchar(45) NULL,
	assay_category varchar(45) NULL,
	assay_code varchar(45) NULL,
	assay_outcome int4 NULL,
	assay_potency varchar(45) NULL,
	assay_result varchar(45) NULL,
	assay_result_std varchar(45) NULL,
	assay_type varchar(255) NULL,
	assay_type_simple_aggregate varchar(45) NULL,
	assay_type_standard varchar(255) NULL,
	clowder_doc_id varchar(65) NULL,
	comment text NULL,
	cytotoxicity varchar(255) NULL,
	data_quality varchar(45) NULL,
	document_number varchar(45) NULL,
	document_source varchar(45) NULL,
	dose_response varchar(45) NULL,
	dtxsid varchar(255) NULL,
	duration varchar(45) NULL,
	genetox_details_hash varchar(255) NULL,
	genetox_details_id int4 NULL,
	genetox_details_uuid varchar(255) NULL,
	genetox_note varchar(255) NULL,
	genetox_results varchar(255) NULL,
	metabolic_activation varchar(45) NULL,
	panel_report varchar(255) NULL,
	protocol_era varchar(45) NULL,
	reference varchar(1024) NULL,
	reference_url varchar(255) NULL,
	sex varchar(45) NULL,
	smiles_2d_qsar text NULL,
	source varchar(45) NULL,
	species varchar(45) NULL,
	species_strain varchar(45) NULL,
	strain varchar(255) NULL,
	title varchar(1024) NULL,
	year int4 NULL,
	CONSTRAINT mv_genetox_details_pkey PRIMARY KEY (id)
);

CREATE TABLE toxval.mv_genetox_summary (
	id int4 NULL,
	export_date timestamp NULL,
	data_version varchar(50) NULL,
	ames varchar(255) NULL,
	clowder_doc_id varchar(65) NULL,
	dtxsid varchar(255) NULL,
	genetox_call varchar(255) NULL,
	genetox_summary_id int4 NULL,
	micronucleus varchar(255) NULL,
	reports_neg int4 NULL,
	reports_other int4 NULL,
	reports_pos int4 NULL
);

CREATE TABLE toxval.mv_toxvaldb (
	id int4 NOT NULL,
	export_date date NULL,
	data_version varchar(50) NULL,
	dtxsid varchar(45) NULL,
	casrn text NULL,
	name text NULL,
	source varchar(255) NULL,
	sub_source varchar(255) NULL,
	toxval_type varchar(255) NULL,
	toxval_type_defn text NULL,
	toxval_subtype varchar(255) NULL,
	toxval_type_supercategory varchar(255) NULL,
	qualifier varchar(255) NULL,
	toxval_numeric float8 NULL,
	toxval_units varchar(255) NULL,
	risk_assessment_class varchar(255) NULL,
	human_eco varchar(255) NULL,
	study_type varchar(255) NULL,
	study_duration_class varchar(255) NULL,
	study_duration_value float8 NULL,
	study_duration_units varchar(255) NULL,
	species_common varchar(255) NULL,
	strain varchar(255) NULL,
	latin_name varchar(255) NULL,
	species_supercategory varchar(255) NULL,
	sex varchar(255) NULL,
	generation varchar(255) NULL,
	lifestage varchar(255) NULL,
	exposure_route varchar(255) NULL,
	exposure_method varchar(255) NULL,
	exposure_form varchar(255) NULL,
	media varchar(255) NULL,
	toxicological_effect text NULL,
	experimental_record varchar(50) NULL,
	study_group varchar(255) NULL,
	long_ref text NULL,
	doi text NULL,
	title text NULL,
	author varchar(255) NULL,
	year varchar(255) NULL,
	guideline varchar(255) NULL,
	quality varchar(255) NULL,
	qc_category text NULL,
	source_hash varchar(45) NULL,
	external_source_id text NULL,
	external_source_id_desc text NULL,
	source_url text NULL,
	subsource_url text NULL,
	stored_source_record varchar(250) NULL,
	toxval_type_original varchar(255) NULL,
	toxval_subtype_original varchar(255) NULL,
	toxval_numeric_original float8 NULL,
	toxval_units_original varchar(255) NULL,
	study_type_original varchar(255) NULL,
	study_duration_class_original varchar(255) NULL,
	study_duration_value_original varchar(255) NULL,
	study_duration_units_original varchar(255) NULL,
	species_original varchar(255) NULL,
	strain_original varchar(255) NULL,
	sex_original varchar(255) NULL,
	generation_original varchar(255) NULL,
	lifestage_original varchar(255) NULL,
	exposure_route_original varchar(255) NULL,
	exposure_method_original varchar(255) NULL,
	exposure_form_original varchar(255) NULL,
	media_original varchar(255) NULL,
	toxicological_effect_original text NULL,
	original_year varchar(255) NULL,
	CONSTRAINT mv_toxvaldb_pkey PRIMARY KEY (id)
);

CREATE TABLE toxval.mv_skin_eye (
	id int4 NOT NULL,
	export_date date NULL,
	data_version varchar(50) NULL,
	authority varchar(45) NULL,
	classification varchar(255) NULL,
	dtxsid varchar(255) NULL,
	endpoint varchar(45) NULL,
	glp text NULL,
	guideline text NULL,
	record_url varchar(1024) NULL,
	reliability varchar(45) NULL,
	result_text varchar(1024) NULL,
	score varchar(45) NULL,
	skin_eye_hash varchar(255) NULL,
	skin_eye_id int4 NULL,
	skin_eye_uuid varchar(255) NULL,
	source varchar(45) NULL,
	species varchar(255) NULL,
	strain varchar(255) NULL,
	study_type varchar(255) NULL,
	year int4 NULL,
	CONSTRAINT mv_skin_eye_pkey PRIMARY KEY (id)
);








