name: deploy-staging

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: staging
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'
        
    - name: Run the Maven clean package
      run: mvn clean package -DskipTests

    - uses: actions/upload-artifact@master
      with:
        name: hazard-jar
        path: ./target
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: staging
      - uses: actions/download-artifact@master
        with:
          name: hazard-jar
          path: ./target
      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_STAGING_SERVICE_USERNAME }}
          cf_password: ${{ secrets.CF_STAGING_SERVICE_KEY }}
          cf_org: epa-ord
          cf_space: ccte-stg
          cf_command: push -f manifest-stg.yml --no-start
          
  bind-db-service:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: Bind app to DB service
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_STAGING_SERVICE_USERNAME }}
          cf_password: ${{ secrets.CF_STAGING_SERVICE_KEY }}
          cf_org: epa-ord
          cf_space: ccte-stg
          cf_command: bind-service ccte-hazard-stg db-prod
          
  restage:
    runs-on: ubuntu-latest
    needs: bind-db-service
    
    steps:
      - name: Restage app
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_STAGING_SERVICE_USERNAME }}
          cf_password: ${{ secrets.CF_STAGING_SERVICE_KEY }}
          cf_org: epa-ord
          cf_space: ccte-stg
          cf_command: restage ccte-hazard-stg
